var urlInteragir="/interagir.php";var span_player_opened=false;function Message(player,numero_page){$("#dialog").empty();$("#dialog").append("<img src=\"/stuff/loading.gif\" style=\"margin-left:140px;\" alt=\"Chargement de la messagerie\">");$("#dialog").dialog("open");$.getJSON(urlInteragir,{"action":"last_msg","joueur":player,"num":numero_page},function(data){if(data!="error"){$("#dialog").empty();$("#dialog").append("<div id=\"liste_messages\" style=\"max-height:300px;overflow:auto;text-align: center;\">"+data.derniers_messages+"</div>");if(data.notifs_en_moins!=0){var notif_header_before=$("a#notifs_header").text();var notifs_mp_before=$("#notifs_mp").children("b").text();if(notifs_mp_before-data.notifs_en_moins<=0){$("#boxInbox").css("background","");}
$("#notifs_mp").children("b").empty();$("#notifs_mp").children("b").append(notifs_mp_before-data.notifs_en_moins);}
$("#dialog").dialog("option","position","center");}});}
function InviteToGame(player){$.post(urlInteragir,{"action":"inviter","joueur":player},function(data){if(data.fait=="ok"){$("#dialog").empty();$("#dialog").append("<b>"+player+"</b> a reçu une invitation à rejoindre la partie dans laquelle vous êtes.");$("#dialog").dialog("option","position","center");$("#dialog").dialog("open");}},'json');}
function EffacerInvit(player,partie){$.post(urlInteragir,{"action":"effacer","joueur":player,"partie":partie},'json');}
function Moderation_rapide(commande,pseudo_a_moderer,acces_modo){if(commande=="mute"){if(confirm("Etes-vous sur de vouloir baîllonner "+pseudo_a_moderer+" ?")){var message_half_typed=$("#message").val();$("#message").val("/mute "+pseudo_a_moderer);sendChat();$("#message").val(message_half_typed);}}
else if(commande=="unmute"){if(confirm("Etes-vous sur de vouloir débaîlloner "+pseudo_a_moderer+" ?")){var message_half_typed=$("#message").val();$("#message").val("/unmute "+pseudo_a_moderer);sendChat();$("#message").val(message_half_typed);}}
else if(commande=="add_bonbons"){$.post(urlInteragir,{"action":commande,"joueur":pseudo_a_moderer},function(data){if(data!="error"){$("#dialog").empty();$("#dialog").append("Confirmation : "+pseudo_a_moderer+" a reçu 10 bonbons et en a désormais <b>"+data.bonbons+"</b>.<br /><br />"+
"<a class=\"lien_simple\" onclick=\"Moderation_rapide('add_bonbons', '"+pseudo_a_moderer+"');\">Lui en donner 10 de plus ?</a>");$("#dialog").dialog("option","position","center");}},'json');}
else if(commande=="display_ban"){$("#dialog").empty();var options_ban='<input  type="hidden" id="pseudoban" value="'+pseudo_a_moderer+'"/>'+
'Durée:<select id="duree_ban"><option value="1">1 heure</option>'+
'<option value="2">2 heures</option>'+
'<option value="3">3 heures</option>'+
'<option value="5">5 heures</option>'+
'<option value="8">8 heures</option>'+
'<option value="24">1 jour</option>';if(acces_modo=='3'){options_ban+='<option value="48">2 jours</option>'+
'<option value="240">10 jours</option>'+
'<option value="720">30 jours</option>'+
'<option value="-1">A vie</option></select>';}
$("#dialog").append(options_ban+'<input  type="submit" value="Bannir '+pseudo_a_moderer+'" onclick="Moderation_rapide(\'submit_ban\', \''+pseudo_a_moderer+'\');" />');$("#dialog").dialog("option","position","center");$("#dialog").dialog("open");}
else if(commande=="submit_ban"){if(confirm("Etes-vous sur de vouloir bannir "+pseudo_a_moderer+" pour la durée choisie ?")){var duree_ban=$('#duree_ban').val();$.post(urlInteragir,{"action":"bannir_joueur","joueur":pseudo_a_moderer,"duree_ban":duree_ban},function(data){if(data!="error"){$("#dialog").empty();$("#dialog").append('Confirmation : le joueur a bien été banni pour la durée demandée.');$("#dialog").dialog("option","position","center");}},'json');}}
else if(commande=="get_last_games"){$("#dialog").empty();$("#dialog").append("<img src=\"/stuff/loading.gif\" style=\"margin-left:140px;\" alt=\"Chargement des dernières parties\">");$("#dialog").dialog("open");$.getJSON(urlInteragir,{"action":commande,"joueur":pseudo_a_moderer},function(data){if(data.fait=="ok"){$("#dialog").empty();$("#dialog").append("<a class='lien_infos' data-profile='"+pseudo_a_moderer+"'>Retour au profil de "+pseudo_a_moderer+"</a>");$("#dialog").append("<div style='padding-top:10px;font-size:14px;'>"+data.last_games+"</div>");$("#dialog").dialog("option","position","center");$("#dialog").dialog("open");}});}
else if(commande=="display_stalk"){$("#dialog").empty();$("#dialog").append("Indiquez la raison de la surveillance : <input type=\"text\" id=\"raison_surveillance\"><br /><input type=\"submit\" id=\"surveillance_submit\" onclick=\"Moderation_rapide('stalk', '"+pseudo_a_moderer+"')\">");$("#dialog").dialog("open");}
else if(commande=="stalk"){$("#surveillance_submit").after(" <img src=\"/stuff/loading_mini.gif\" style=\"margin-left:140px;\" alt=\"Chargement\">");if($("#raison_surveillance").length){var raison_surveillance=$("#raison_surveillance").val();}
else{var raison_surveillance="none";}
if(raison_surveillance.length>3){$.post(urlInteragir,{"action":commande,"joueur":pseudo_a_moderer,"raison":raison_surveillance},function(data){if(data.fait=="added"){var message_de_confirmation="<div style='padding-top:10px;font-size:14px;'>Confirmation : "+pseudo_a_moderer+" a bien été ajouté à la liste des <b>joueurs sous surveillance</b>.</div>";}
else if(data.fait=="removed"){var message_de_confirmation="<div style='padding-top:10px;font-size:14px;'>Confirmation : "+pseudo_a_moderer+" a bien été retiré de la liste des <b>joueurs sous surveillance</b>.</div>";}
$("#dialog").empty();$("#dialog").append("<a class='lien_infos' data-profile='"+pseudo_a_moderer+"'>Retour au profil de "+pseudo_a_moderer+"</a>");$("#dialog").append(message_de_confirmation);$("#dialog").dialog("option","position","center");$("#dialog").dialog("open");},'json');}
else{$("#dialog").empty();$("#dialog").append("Indiquez la raison* de la surveillance : <input type=\"text\" id=\"raison_surveillance\"><br /><input type=\"submit\" id=\"surveillance_submit\" onclick=\"Moderation_rapide('stalk', '"+pseudo_a_moderer+"')\"><br /><br />* Obligatoire");$("#dialog").dialog("open");}}
else if(commande=="past_facts"){$("#dialog").empty();$("#dialog").append("<img src=\"/stuff/loading.gif\" style=\"margin-left:140px;\" alt=\"Chargement des antécédents\">");$("#dialog").dialog("open");$.getJSON(urlInteragir,{"action":commande,"joueur":pseudo_a_moderer},function(data){if(data.fait=="ok"){$("#dialog").empty();$("#dialog").append("<a class='lien_infos' data-profile='"+pseudo_a_moderer+"'>Retour au profil de "+pseudo_a_moderer+"</a>");$("#dialog").append("<div style='padding-top:10px;font-size:12px;'>"+data.past_facts+"</div>");$("#dialog").dialog("option","position","center");$("#dialog").dialog("open");}});}
else if(commande=="get_same_ip_accounts"){$("#dialog").empty();$("#dialog").append("<img src=\"/stuff/loading.gif\" style=\"margin-left:140px;\" alt=\"Chargement des comptes sur la même IP\">");$("#dialog").dialog("open");$.getJSON(urlInteragir,{"action":commande,"joueur":pseudo_a_moderer},function(data){if(data.fait=="ok"){$("#dialog").empty();$("#dialog").append("<a class='lien_infos' data-profile='"+pseudo_a_moderer+"'>Retour au profil de "+pseudo_a_moderer+"</a>");$("#dialog").append("<div style='padding-top:10px;font-size:12px;'>"+data.same_ip_accounts+"</div>");$("#dialog").dialog("option","position","center");$("#dialog").dialog("open");}
else{$("#dialog").empty();$("#dialog").append("<a class='lien_infos' data-profile='"+pseudo_a_moderer+"'>Retour au profil de "+pseudo_a_moderer+"</a>");$("#dialog").append("<div style='padding-top:10px;font-size:12px;'>Vous ne pouvez pas consulter cette information (Superviseurs ONLY).</div>");$("#dialog").dialog("option","position","center");$("#dialog").dialog("open");}});}
else if(commande=="remove_signature"){if(confirm("Etes-vous sur de vouloir effacer la signature de "+pseudo_a_moderer+" ?")){$.getJSON(urlInteragir,{"action":commande,"joueur":pseudo_a_moderer},function(data){if(data.fait=="ok"){window.location.reload();}});}}}
function Handle_clics_msg(){$(".lire_message").unbind('click');$(".lire_message").click(function(){if($(this).children(".fil_1").length){var type_fil=1;}
else{var type_fil=2;}
if($(this).children(".fil_"+type_fil).children(".notif_du_fil").length){$(this).children(".fil_"+type_fil).children(".notif_du_fil").fadeOut("normal");var right_mps_b4=$("span#right_mps").text();var content_mps_b4=$(this).children(".fil_"+type_fil).children(".notif_du_fil").children("span#content_mps").text();right_mps_after=right_mps_b4-content_mps_b4;$("span#right_mps").empty();$("span#right_mps").append(right_mps_after);}});}
function afficherLightboxTuto(pseudo,tutoIDS){$('body').prepend("<div id='lightboxWebpageHider' style='position: fixed;z-index: 1;top:0;bottom:0;left:0;right:0;background-color:#eee;opacity:0.9;'></div>");$("#dialog").empty();$("#dialog").append("<div style='text-align: center;min-height: 400px;'>"+
"<img src='stuff/tuto/header_tuto.png' style='width:600px; height:100px;border:1px solid black;margin-bottom:40px;'><br />"+
"<b style='font-size: 20px;color: #B90202;'>Bienvenue, "+pseudo+" !</b><br />"+
"<div style='margin-top:75px;margin-bottom: 20px;'><b>Vous êtes nouveau sur le site.</b><br />Voulez-vous prendre part à un <b>court tutoriel</b> ?</div>"+
"<div><a target='_blank' class='tutoBoutonOui' href='jeu/index.php?partie="+tutoIDS+"'>Oui (recommandé)</a> <a class='tutoBoutonNon'>Non, j'ai déjà joué</a></div>"+
"</div>");$(".ui-dialog .ui-dialog-titlebar-close").hide();$("a.tutoBoutonNon").bind("click",function(){$("#lightboxWebpageHider").remove();$("#dialog").dialog("close");});$('.ui-widget-overlay').unbind("click");$("#dialog").dialog("option","position","center");$('.ui-widget-overlay').unbind("click");$("#dialog").dialog("open");$('.ui-widget-overlay').unbind("click");}
$(document).ready(function(){$('body').prepend("<div id=\"dialog\" title=\"Loups-Garous-en-ligne\"></div>");$('body').prepend("<div id=\"dialog_moderation\" title=\"Loups-Garous-en-ligne\"></div>");$('body').prepend("<div id=\"dialog_cal\" title=\"Loups-Garous-en-ligne\"></div>");$("#dialog").dialog({autoOpen:false,show:{effect:'fade'},hide:{effect:'fade'},modal:true,width:650,close:function(event,ui){$('#wrap').show();},open:function(event,ui){$('.ui-widget-overlay').bind('click',function(){$("#dialog").dialog('close');});}});$("#dialog_moderation").dialog({autoOpen:false,show:{effect:'fade'},hide:{effect:'fade'},modal:true,width:650,close:function(event,ui){$('#wrap').show();},open:function(event,ui){$('.ui-widget-overlay').bind('click',function(){$("#dialog_moderation").dialog('close');});}});$("#dialog_cal").dialog({autoOpen:false,show:{effect:'fade'},hide:{effect:'fade'},modal:true,width:1000,close:function(event,ui){$('#wrap').show();},open:function(event,ui){$('.ui-widget-overlay').bind('click',function(){$("#dialog_cal").dialog('close');});}});Handle_clics_msg();});